meta_product_name: "Me-oW"
meta_title: "Me-oW - Empowering women through mentorship"
meta_description: "A goal-centric app that connects female mentors and mentees from around the world based on their personal and professional interests"
meta_image: "homepage.jpg"
twitter_account: "@product_twitter_account"
